### ISSUE TITLE
Import to cursor changes structure

### ISSUE THREAD

**Issue by rschummer** [atlopes/csv#3]
I am seeing that after an Import(), that the structure of the cursor is altered. For instance, a C(30) field in the cursor before the import is now C(8) because the longest string in the column is 8 characters. Is this behavior avoidable? Here is the code I am running with a table I created called customer.DBF. I create a cursor using a select statement that filters to no records. Structure carries over for the most part. Export Customer to CSV works like a charm. Import, look at LIST STRU afterwards and it is altered. Seems odd that it would alter existing cursor or table. I know it does this when you have it create the structure on the fly without providing the object guidance.

```
DO csv.prg

LOCAL loCSV AS CSVProcessor, ;
      lcOldSafety
      
loCSV = CREATEOBJECT("CSVProcessor")

USE data\customer SHARED AGAIN 

SELECT * FROM customer WHERE 1=0 INTO CURSOR curCustomers READWRITE 

* NOTE: LIST STRUCTURE shows cursor with structure close to Customer table 
* (small exceptions like auto increment does not carry, naturally)

* Export to CSV file, demo note: check results returned
SELECT customer
loCSV.Export("customerwithmemo.CSV")

* Check out the exported data and surprise, memo exports
MODIFY FILE customerwithmemo.CSV NOEDIT RANGE 1,1

SELECT curCustomers

* Cursor Import the CSV file with memo data
loCSV.Import("customerwithmemo.CSV", "curCustomers")

BROWSE NORMAL NOCAPTIONS 

* NOTE: LIST STRUCTURE shows cursor with structure where character columns are smaller 
* in line with longest string for the column.

RETURN
```

**Comment by atlopes** [comment]
Rick, to import into an existing cursor:
```foxpro
* change the .Import() call to

loCSV.WorkArea = "curCustomers"
loCSV.Import("customerwithmemo.CSV")     && just the CSV source file with a given work area enters append mode
```

**Comment by rschummer** [comment]
Thanks António, worked perfect. Much appreciated.
